-- แก้ไขสิทธิ์การเข้าถึงตารางสินค้า (Products Permissions)
-- สาเหตุที่เพิ่มสินค้าไม่ได้ อาจเกิดจาก Script ก่อนหน้านี้รันไม่จบ ทำให้สิทธิ์การเพิ่มสินค้ายังไม่ถูกสร้างครับ

-- 1. สร้างตารางสินค้า (เผื่อยังไม่มี)
CREATE TABLE IF NOT EXISTS public.products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  price numeric,
  image_url text,
  category text,
  description text,
  stock integer default 0
);

-- 2. เปิดใช้งานระบบความปลอดภัย RLS
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- 3. ลบสิทธิ์เก่าทิ้ง (เพื่อป้องกันการซ้ำ)
DROP POLICY IF EXISTS "Enable read access for all users" ON public.products;
DROP POLICY IF EXISTS "Enable insert for all" ON public.products;
DROP POLICY IF EXISTS "Enable update for all" ON public.products;
DROP POLICY IF EXISTS "Enable delete for all" ON public.products;

-- 4. เพิ่มสิทธิ์ใหม่ (อนุญาตให้ทุกคน อ่าน/เพิ่ม/แก้ไข/ลบ ได้)
-- หมายเหตุ: ในระบบจริงควรจำกัดสิทธิ์เฉพาะ Admin แต่ตอนนี้เปิดหมดเพื่อให้ทดสอบผ่านก่อนครับ
CREATE POLICY "Enable read access for all users" ON public.products FOR SELECT USING (true);
CREATE POLICY "Enable insert for all" ON public.products FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for all" ON public.products FOR UPDATE USING (true);
CREATE POLICY "Enable delete for all" ON public.products FOR DELETE USING (true);
