-- 1. Categories Table
CREATE TABLE IF NOT EXISTS public.categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    name text NOT NULL,
    slug text NOT NULL UNIQUE,
    description text
);

-- 2. Brands Table
CREATE TABLE IF NOT EXISTS public.brands (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    name text NOT NULL,
    slug text NOT NULL UNIQUE,
    logo_url text
);

-- 3. Junction Table: Categories <-> Brands
-- (e.g. CPU category has Intel, AMD brands)
CREATE TABLE IF NOT EXISTS public.category_brands (
    category_id bigint REFERENCES public.categories(id) ON DELETE CASCADE,
    brand_id bigint REFERENCES public.brands(id) ON DELETE CASCADE,
    PRIMARY KEY (category_id, brand_id)
);

-- 4. Function: Specification Keys (Definitions per category)
-- e.g. Category 'CPU' has spec keys 'Socket', 'TDP'
CREATE TABLE IF NOT EXISTS public.category_specs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id bigint REFERENCES public.categories(id) ON DELETE CASCADE,
    name text NOT NULL, -- e.g. 'Socket', 'Base Clock'
    unit text, -- e.g. 'GHz', 'Watts'
    options text[] -- Optional: predefined options for dropdowns
);

-- 5. Product Specifications Values
-- Stores the actual values for a product's specs
CREATE TABLE IF NOT EXISTS public.product_specs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id bigint REFERENCES public.products(id) ON DELETE CASCADE,
    spec_id bigint REFERENCES public.category_specs(id) ON DELETE CASCADE,
    value text,
    UNIQUE(product_id, spec_id)
);

-- 6. Update Products Table to link foreign keys
ALTER TABLE public.products 
ADD COLUMN IF NOT EXISTS category_id bigint REFERENCES public.categories(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS brand_id bigint REFERENCES public.brands(id) ON DELETE SET NULL;

-- Enable RLS
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.brands ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.category_brands ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.category_specs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_specs ENABLE ROW LEVEL SECURITY;

-- Policies (Public Read, Admin Write - simplified to Public Write for now as per dev mode)
CREATE POLICY "Public Read Categories" ON public.categories FOR SELECT USING (true);
CREATE POLICY "Public Read Brands" ON public.brands FOR SELECT USING (true);
CREATE POLICY "Public Read CategoryBrands" ON public.category_brands FOR SELECT USING (true);
CREATE POLICY "Public Read CategorySpecs" ON public.category_specs FOR SELECT USING (true);
CREATE POLICY "Public Read ProductSpecs" ON public.product_specs FOR SELECT USING (true);

-- Allow Insert/Update for authenticated users (or everyone for dev/demo simplicity as per previous pattern)
CREATE POLICY "Public Write Categories" ON public.categories FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Write Brands" ON public.brands FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Write CategoryBrands" ON public.category_brands FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Write ProductSpecs" ON public.product_specs FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Write CategorySpecs" ON public.category_specs FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update ProductSpecs" ON public.product_specs FOR UPDATE USING (true);

-- SEED DATA (Categories)
INSERT INTO public.categories (name, slug) VALUES
('สินค้าทั่วไป', 'general'),
('โน๊ตบุ๊ค', 'notebook'),
('จอมอนิเตอร์', 'monitor'),
('แท็บเล็ต', 'tablet'),
('ซีพียู', 'cpu'),
('การ์ดจอ', 'gpu'),
('เมนบอร์ด', 'motherboard'),
('แรม', 'ram'),
('ฮาร์ดดิสก์ และ เอสเอสดี', 'storage'),
('พาวเวอร์ซัพพลาย', 'psu'),
('เคส', 'case'),
('ชุดระบายความร้อน', 'cooling'),
('คีย์บอร์ด', 'keyboard'),
('เมาส์', 'mouse'),
('ลำโพง', 'speaker'),
('เกมมิ่งเกียร์', 'gaming-gear')
ON CONFLICT (slug) DO NOTHING;

-- SEED DATA (Brands - Example based on subcategories)
INSERT INTO public.brands (name, slug) VALUES
('INTEL', 'intel'),
('AMD', 'amd'),
('NVIDIA', 'nvidia'),
('Apple', 'apple'),
('Samsung', 'samsung'),
('Logitech', 'logitech'),
('Razer', 'razer'),
('Kingston', 'kingston'),
('Corsair', 'corsair'),
('Asus', 'asus'),
('MSI', 'msi'),
('Gigabyte', 'gigabyte')
ON CONFLICT (slug) DO NOTHING;

-- Link logic would happen in application or manual mapping
-- For example, link CPU category to Intel/AMD brands
DO $$
DECLARE
    cat_cpu bigint;
    brand_intel bigint;
    brand_amd bigint;
BEGIN
    SELECT id INTO cat_cpu FROM public.categories WHERE slug = 'cpu';
    SELECT id INTO brand_intel FROM public.brands WHERE slug = 'intel';
    SELECT id INTO brand_amd FROM public.brands WHERE slug = 'amd';
    
    IF cat_cpu IS NOT NULL AND brand_intel IS NOT NULL THEN
        INSERT INTO public.category_brands (category_id, brand_id) VALUES (cat_cpu, brand_intel) ON CONFLICT DO NOTHING;
    END IF;
    
    IF cat_cpu IS NOT NULL AND brand_amd IS NOT NULL THEN
        INSERT INTO public.category_brands (category_id, brand_id) VALUES (cat_cpu, brand_amd) ON CONFLICT DO NOTHING;
    END IF;
END $$;
