-- 1. อัปเดตตาราง Profiles (เพิ่มคอลัมน์ใหม่)
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS birth_date date;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS line_id text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS facebook text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS instagram text;

-- 2. สร้างตาราง Addresses ใหม่ (แบบที่รองรับที่อยู่ไทย)
-- หมายเหตุ: คำสั่งนี้จะลบข้อมูลที่อยู่เก่า (ถ้ามี) เพื่อสร้างโครงสร้างใหม่
DROP TABLE IF EXISTS public.addresses;

CREATE TABLE public.addresses (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  recipient_name text,
  phone text,
  address text,
  district text,
  province text,
  zipcode text,
  is_default boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- เปิดใช้งานระบบความปลอดภัย (RLS)
ALTER TABLE public.addresses ENABLE ROW LEVEL SECURITY;

-- สร้างสิทธิ์การเข้าถึงข้อมูล (Policies)
CREATE POLICY "Users can view own addresses" ON public.addresses FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own addresses" ON public.addresses FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own addresses" ON public.addresses FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own addresses" ON public.addresses FOR DELETE USING (auth.uid() = user_id);
