-- ==========================================
-- 1. Reset (Optional: Use with caution in production)
-- ==========================================
-- DROP TABLE IF EXISTS public.order_items CASCADE;
-- DROP TABLE IF EXISTS public.orders CASCADE;
-- DROP TABLE IF EXISTS public.profiles CASCADE;
-- DROP TABLE IF EXISTS public.products CASCADE;

-- ==========================================
-- 2. Products Table (Existing)
-- ==========================================
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  price numeric,
  image_url text,
  category text,
  description text,
  stock integer default 0
);

-- ==========================================
-- 3. Profiles Table (For Users)
-- Link to Supabase Auth.users
-- ==========================================
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text,
  full_name text,
  avatar_url text,
  role text default 'customer' check (role in ('customer', 'admin')),
  phone text,
  address text,
  birth_date date,
  line_id text,
  facebook text,
  instagram text,
  updated_at timestamp with time zone
);

-- Toggle RLS
alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on public.profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on public.profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on public.profiles for update
  using ( auth.uid() = id );

-- ==========================================
-- 4. Orders Table
-- ==========================================
create table public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  status text default 'pending', -- pending, paid, shipped, completed, cancelled
  total_amount numeric,
  shipping_address text,
  payment_method text,
  cancel_reason text,
  tracking_number text
);

alter table public.orders enable row level security;

create policy "Users can view own orders"
  on public.orders for select
  using ( auth.uid() = user_id );

create policy "Users can create orders"
  on public.orders for insert
  with check ( auth.uid() = user_id );

-- ==========================================
-- 5. Order Items Table
-- ==========================================
create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references public.orders(id) on delete cascade,
  product_id bigint references public.products(id),
  quantity integer default 1,
  price_at_purchase numeric
);

alter table public.order_items enable row level security;

create policy "Users can view own order items"
  on public.order_items for select
  using ( 
    exists (
      select 1 from public.orders
      where public.orders.id = public.order_items.order_id
      and public.orders.user_id = auth.uid()
    )
  );

-- ==========================================
-- 6. Automations (Triggers)
-- Automatically create profile on signup
-- ==========================================
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger the function every time a user is created
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- ==========================================
-- 7. Permissions for Scraper/Products
-- ==========================================
alter table public.products enable row level security;

-- Allow read for everyone
drop policy if exists "Enable read access for all users" on public.products;
create policy "Enable read access for all users" on public.products for select using (true);

-- Allow insert/update for everyone (DEV ONLY) - or restrict to 'admin' role in production
drop policy if exists "Enable insert for all" on public.products;
create policy "Enable insert for all" on public.products for insert with check (true);

-- ==========================================
-- 8. Categories Table
-- ==========================================
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  slug text not null unique,
  image_url text,
  parent_id bigint references public.categories(id)
);

alter table public.categories enable row level security;
-- Allow read for everyone
drop policy if exists "Enable read access for all users" on public.categories;
create policy "Enable read access for all users" on public.categories for select using (true);

-- ==========================================
-- 9. Reviews Table
-- ==========================================
create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  product_id bigint references public.products(id) not null,
  rating integer check (rating >= 1 and rating <= 5) not null,
  comment text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.reviews enable row level security;
drop policy if exists "Reviews are viewable by everyone" on public.reviews;
create policy "Reviews are viewable by everyone" on public.reviews for select using (true);
drop policy if exists "Users can insert own reviews" on public.reviews;
create policy "Users can insert own reviews" on public.reviews for insert with check (auth.uid() = user_id);
drop policy if exists "Users can update own reviews" on public.reviews;
create policy "Users can update own reviews" on public.reviews for update using (auth.uid() = user_id);
drop policy if exists "Users can delete own reviews" on public.reviews;
create policy "Users can delete own reviews" on public.reviews for delete using (auth.uid() = user_id);

-- ==========================================
-- 10. Wishlist Table
-- ==========================================
create table if not exists public.wishlist (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  product_id bigint references public.products(id) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, product_id)
);

alter table public.wishlist enable row level security;
drop policy if exists "Users can view own wishlist" on public.wishlist;
create policy "Users can view own wishlist" on public.wishlist for select using (auth.uid() = user_id);
drop policy if exists "Users can insert into own wishlist" on public.wishlist;
create policy "Users can insert into own wishlist" on public.wishlist for insert with check (auth.uid() = user_id);
drop policy if exists "Users can delete from own wishlist" on public.wishlist;
create policy "Users can delete from own wishlist" on public.wishlist for delete using (auth.uid() = user_id);

-- ==========================================
-- 11. Cart & Cart Items (Persistent Cart)
-- ==========================================
create table if not exists public.carts (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.carts enable row level security;
drop policy if exists "Users can view own cart" on public.carts;
create policy "Users can view own cart" on public.carts for select using (auth.uid() = user_id);
drop policy if exists "Users can insert own cart" on public.carts;
create policy "Users can insert own cart" on public.carts for insert with check (auth.uid() = user_id);

create table if not exists public.cart_items (
  id bigint generated by default as identity primary key,
  cart_id bigint references public.carts(id) on delete cascade not null,
  product_id bigint references public.products(id) not null,
  quantity integer default 1 check (quantity > 0),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(cart_id, product_id)
);

alter table public.cart_items enable row level security;
drop policy if exists "Users can view own cart items" on public.cart_items;
create policy "Users can view own cart items" on public.cart_items for select using (
  exists (select 1 from public.carts where id = cart_items.cart_id and user_id = auth.uid())
);
drop policy if exists "Users can insert own cart items" on public.cart_items;
create policy "Users can insert own cart items" on public.cart_items for insert with check (
   exists (select 1 from public.carts where id = cart_items.cart_id and user_id = auth.uid())
);
drop policy if exists "Users can update own cart items" on public.cart_items;
create policy "Users can update own cart items" on public.cart_items for update using (
   exists (select 1 from public.carts where id = cart_items.cart_id and user_id = auth.uid())
);
drop policy if exists "Users can delete own cart items" on public.cart_items;
create policy "Users can delete own cart items" on public.cart_items for delete using (
   exists (select 1 from public.carts where id = cart_items.cart_id and user_id = auth.uid())
);

-- ==========================================
-- 12. Addresses Table
-- ==========================================
create table if not exists public.addresses (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  recipient_name text,
  phone text,
  address text,
  district text,
  province text,
  zipcode text,
  is_default boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.addresses enable row level security;
drop policy if exists "Users can view own addresses" on public.addresses;
create policy "Users can view own addresses" on public.addresses for select using (auth.uid() = user_id);
drop policy if exists "Users can insert own addresses" on public.addresses;
create policy "Users can insert own addresses" on public.addresses for insert with check (auth.uid() = user_id);
drop policy if exists "Users can update own addresses" on public.addresses;
create policy "Users can update own addresses" on public.addresses for update using (auth.uid() = user_id);
drop policy if exists "Users can delete own addresses" on public.addresses;
create policy "Users can delete own addresses" on public.addresses for delete using (auth.uid() = user_id);
